pipeline {
    agent any

    environment {
        NAME = 'andrey'
    }

    parameters {
        choice choices: ['dev', 'prod'], name: 'select_environment'
    }

    stages {
        stage('build') {
            steps {
                bat 'mvn clean package -DskipTests=true'
            }
        }

        stage ('test') {
            when {
                expression{params.select_environment == 'dev'}
            }
            parallel {
                stage ('testA'){
                    steps {
                        echo " This is testA"
                        bat "mvn test"
                    }
                }
                stage ('testB'){
                    steps {
                        echo " This is testB"
                        bat "mvn test"
                    }
                }
            }
            post {
                success {
                    archiveArtifacts artifacts: '**/target/*.jar'
                }
            }
        }
    }
}