pipeline {
    agent any

    environment {
        NAME = 'andrey'
    }

    parameters {
        string defaultValue: 'shablov', name: 'LASTNAME'
    }

    stages {
        stage('Build') {
            steps {
                bat 'mvn clean package'
                echo "hello ${NAME}  ${params.LASTNAME}"
            }
        }

        stage ('test') {
            parallel {
                stage ('testA'){
                    steps {
                        echo " This is testA"
                    }
                }
                stage ('testB'){
                    steps {
                        echo " This is testB"
                    }
                }
            }
            post {
                success {
                    archiveArtifacts artifacts: '**/target/*.jar'
                }
            }
        }
    }
}